// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrGsRDl_vJdqnsiuyDu4UpkeIyFptiMGo',
    appId: '1:1094314533085:web:a0d4ab2f8768f6072e7b34',
    messagingSenderId: '1094314533085',
    projectId: 'kupon-qurban',
    authDomain: 'kupon-qurban.firebaseapp.com',
    databaseURL: 'https://kupon-qurban-default-rtdb.firebaseio.com',
    storageBucket: 'kupon-qurban.firebasestorage.app',
    measurementId: 'G-998K2BBS32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfuo6a05qp5rQ0uEiFYH9lFp9JMPard24',
    appId: '1:1094314533085:android:0d8b26c3d1b661ca2e7b34',
    messagingSenderId: '1094314533085',
    projectId: 'kupon-qurban',
    databaseURL: 'https://kupon-qurban-default-rtdb.firebaseio.com',
    storageBucket: 'kupon-qurban.firebasestorage.app',
  );
}
