name: Flutter web build

on: 
  push:
    branches: [ master ]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
    - name: Set up Flutter Web
      uses: bluefireteam/flutter-gh-pages@v8
      with:
        baseHref: /Flutter-Realtime-Database-Firebase/
        webRenderer: canvaskit
    
    
